SELECT
    INTKEY,
    CASE
        WHEN PROPERTYDAMAGEONLY = 'Y' THEN 1
        ELSE (COUNT(INJURIES) * 2) + (COUNT(SERIOUSINJURIES) * 5) + (COUNT(FATALITIES) * 10) 
    END AS severity_score
FROM collisions
WHERE INTKEY IS NOT NULL
GROUP BY INTKEY
ORDER BY severity_score DESC;